### ISSUE TITLE
Assert failure with compile optimizations

### ISSUE THREAD

**Issue by mathisloge** [nisennenmondai/libwecan#1]
If you compile the tests with `gcc -g -Wall -Wextra -pedantic-errors tests/tests.c -o bin/tests -O3` 
you get the error message 
```
===========================================================
ENCODE DECODE MOTOROLA 32 bits double negative value
===========================================================

step 9.2

value to be encoded: -50.6164129

encoded frame: 00 00 00 00 00 00 00 00

decoded value:       0.0000000
tests: tests/tests.c:736: main: Assertion `physical_value == decode_double(frame, startbit, length, MOTOROLA, factor, offset)' failed.
Aborted (core dumped)
```
The error occurs at optimization levels 1-3 and s (size optimization).

**Comment by nisennenmondai** [comment]
Hello,
Thank you for your input, I'll investigate this issue when I have a bit of time

nisen

**Comment by nisennenmondai** [comment]
bug is fixed, I don't know why but compiler is doing some weird optimization when the value past in encode functions is negative, resulting in a 0 being written in the frame. physical value should be declared as volatile to force compiler not to optimize this variable, let me know if this works for you so i can close this issue.

nisen,

**Comment by mathisloge** [comment]
Hey sorry, 
the volatile fix works. Thanks

**Comment by nisennenmondai** [comment]
> Hey sorry,
> the volatile fix works. Thanks

I believe I found the real problem and it is quite interesting see this link bellow if you want more information

https://www.embeddeduse.com/2013/08/25/casting-a-negative-float-to-an-unsigned-int/

So basically I think the compiler is doing an implicit double cast float -> int -> unsigned int, that is why  a -50.5756 will give us 505756 without rounding the value (not a safe way to cast btw, i have to fix that). But with optimization activated it is doing float -> unsigned int directly thus skipping the int cast. I am not 100% sure but this is my best guess.

**Comment by mathisloge** [comment]
Thanks for sharing the article. It is really interesting, Sometimes casting can be a real thieve of time. 

At the moment I have no time to look at the problem in the code, but it sounds like a possible cause.
